AWSTemplateFormatVersion: '2010-09-09'
Description: Enable AWS SSM Preferences
# Parameters:
  # EnvironmentName:
  #   Description: An environment name that is prefixed to resource names
  #   Type: String
  #   AllowedValues:
  #     - ootb-t4t
  #     - dev-t4t
  #     - qa-t4t
  #     - prod-t4t
  # KMSId:
  #   Type: String
  #   Description: KMSId
  # CWLogs: 
  #   Type: String
  #   Description: CloudWatch Logs you want to log SSM 

Resources:
  SystemsManagerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ssm/managed-instance/SessionPreferences
      Type: String
      Value: |
        {
          "SessionPreferences": [
            {
              "SettingName": "IdleTimeout",
              "SettingValue": "120"
            },
            {
              "SettingName": "KmsKeyId",
              "SettingValue": "arn:aws:kms:us-east-2:627131731129:key/836aaaf1-1ce5-4be9-bbfd-570daad86d85"
            },
            {
              "SettingName": "CloudWatchLogGroupName",
              "SettingValue": "SSM-Log-Group"
            },
            {
              "SettingName": "StreamSession",
              "SettingValue": "true"
            },
            {
              "SettingName": "ListLogs",
              "SettingValue": "true"
            }
          ]
        }

Outputs:
  SystemsManagerParameterName:
    Description: Name of the SSM Parameter
    Value: !Ref SystemsManagerParameter
